spring:
    datasource:
        url: jdbc:mysql://awseb-e-25gpm2bdnv-stack-awsebrdsdatabase-bqb2avn4dcq1.cvm460asgxo6.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
        username: fastcam
        password: fastcam1!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
    cache:
        type: redis
        redis:
            host: fc-board-redis-7sjt2d.serverless.apn2.cache.amazonaws.com
            post: 6379
